# profiles.toml
[dev]
llm_provider = "anthropic"
llm_model = "claude-3-5-haiku-latest"
hookset_before = [
  "langops.hooks.log_request"
]
hookset_after = [
  "langops.hooks.mongo_insert",
  "langops.hooks.langfuse_track",
  "langops.hooks.guard_output",
  "langops.hooks.persist_sql",
]



[test]
llm_provider = "anthropic"
llm_model = "claude-3-5-sonnet-20241022"
hookset_before = [
  "langops.hooks.log_request"
]
hookset_after = [
  "langops.hooks.langfuse_track",
  "langops.hooks.guard_output",
]





 